### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by YamatoSecurity** [fukusuket/base64-utf-detect#1]
@fukusuket Thanks for this! I am getting a crash:
```
thread 'main' panicked at src/main.rs:118:42:
called `Result::unwrap()` on an `Err` value: DeserializationError(InvalidEvtxRecordHeaderMagic { magic: [0, 0, 0, 0] })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you checking! I fixed it! Could you check this?🙏
https://github.com/fukusuket/base64-check/commit/addcda46aad4d46e3bc61a9f74d6af545a8de6e5

**Comment by YamatoSecurity** [comment]
It's fixed now. Thanks so much!
