### ISSUE TITLE
output in CSV?

### ISSUE THREAD

**Issue by YamatoSecurity** [fukusuket/base64-utf-detect#2]
@fukusuket Could you output in CSV so I can filter on the types? I want to run this against lots of `.evtx` files so the output is hard to read. For example: `"Possible Base64 + UTF-8", <filename>, <text>`

Headers: `Type, Filename, Text`

**Comment by fukusuket** [comment]
@YamatoSecurity 
I implemented csv output feature! (Simply output output.csv in the current directory) Could you check it?🙏
e045191ac1adf62d7df96045b284b80dda9ebb3b

**Comment by fukusuket** [comment]
I updated columns!(added original text column)
``Type, Filename, Decoded Text, Orignal  Text``

**Comment by YamatoSecurity** [comment]
Thanks!
